### ISSUE TITLE
Add an unlisted observatory

### ISSUE THREAD

**Issue by mmk8a** [mkelley/elevation#3]
I'd like to be able to manually enter the latitude and longitude of an observatory in case it isn't one of your presets.

**Comment by mkelley** [comment]
Done.  Any other observatories you want in a hot button?

**Comment by mmk8a** [comment]
I was going to say La Palma, but I see you've already added it. I don't ever use McDonald, but given your frequent collaboration with Adam it might be good to add.  I don't see a point to add other closely spaced places like KPNO or APO since DCT will do for planning purposes. And VLT will work for various Chilean observatories.

**Comment by mkelley** [comment]
Fixed!
