### ISSUE TITLE
Galactic latitude

### ISSUE THREAD

**Issue by mmk8a** [mkelley/elevation#52]
It would be helpful if galactic latitude could be displayed (or toggled on) in the target table.

**Comment by mkelley** [comment]
I agree.  There's probably a simple formula for it.

**Comment by mmk8a** [comment]
Galactic longitude and latitude are option 33 in Horizons. Hopefully that makes it easier to implement?

**Comment by mkelley** [comment]
Except that the ephemerides are from the MPC.  Horizons support is at least a year away (waiting for them to release a new API).

**Comment by mmk8a** [comment]
I was waiting to go back to my office to get you the equations for this calculation out of a book, but I found the book online. See topic 29 (pages 56-58):
https://www.iaa.csic.es/~dani/ebooks/Astrophysics/2011%20-%20Practical%20Astronomy%20with%20your%20Calculator%20or%20Spreadsheet_4thEd%20-%20DUFFETT-SMITH.pdf

**Comment by mkelley** [comment]
Updated, thanks @mmk8a !
